package com.example.usersmicroservice.Tables;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

import java.util.Date;

@Data
@DynamoDBTable(tableName = "users")
public class User {


    @NotBlank(message = "Email cannot be empty")
    @DynamoDBHashKey
    private String email;


    @NotBlank(message = "Password cannot be empty")
    @DynamoDBAttribute(attributeName = "password")
    private String password;
}